/* sample.c
*/

/* Program generated by Identity Systems.
 *
 * The SSANAME3 development environment must be established before compiling
 * and linking this sample. Refer to the SSANAME3 documentation for details.
 *
 * Microsoft Windows
 * =================
 * To generate an executable use the command below
 *  cl -Fo<FILENAME>.obj -I%SSATOP%\h -c <FILENAME>.c
 *  cl -Fe<FILENAME>.exe <FILENAME>.obj -link %SSATOP%\lib\stssan3cl.lib
 * SSATOP usually refers to the top level of the SSA-NAME3
 * installation, typically 'C:\ids\nm3'
 *
 * Unix systems
 * ============
 * To generate an executable use the commands below
 *  $SSACCCMD $SSACCFLAGS -c -o <FILENAME>.o <FILENAME>.c
 *  $SSALINKCMD <FILENAME> <FILENAME>.o -L$SSATOP/bin -lssan3cl $SSALLIBS
 * OS/390 Unix System Services
 *  $SSACCCMD $SSACCFLAGS -c -o <FILENAME>.o <FILENAME>.c
 *  $SSALINKCMD sample sample.o $SSALIB/libssan3cl.x
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ssan3cl.h"

#define rangeof(arr)  (sizeof(arr)/sizeof((arr)[0]))

static long test_ssa_open (
  long    sockh,
  long    *session_id,
  char    *sysName,
  char    *population,
  char    *controls)
{
  long    rc;
  char    rsp_code[SSA_SI_RSP_SZ];
  char    ssa_msg[SSA_SI_SSA_MSG_SZ];

  printf ("------ ssan3_open ------\n");
  printf ("Session Id       : %ld\n", *session_id);
  printf ("System           : %s\n", sysName);
  printf ("Population       : %s\n", population);
  printf ("Controls         : %s\n", controls);

  rc = ssan3_open (sockh,
    session_id,
    sysName,
    population,
    controls,
    rsp_code,
    SSA_SI_RSP_SZ,
    ssa_msg,
    SSA_SI_SSA_MSG_SZ);
  if (rc < 0) {
    printf ("rc               : %ld\n", rc);
    rc = 1;
    goto ret;
  }
  if (rsp_code[0] != '0') {
    printf ("rsp_code         : %s\n", rsp_code);
    printf ("ssa_msg          : %s\n", ssa_msg);
    rc = 1;
    goto ret;
  }
  printf ("\n");
  printf ("Session Id       : %ld\n", *session_id);
  printf ("rsp_code         : %s\n", rsp_code);
  printf ("ssa_msg          : %s\n", ssa_msg);
  rc = 0;
  goto ret;

ret:
  return (rc);
}

static long test_ssa_get_keys (
  long    sockh,
  long    *session_id,
  char    *sysName,
  char    *population,
  char    *controls,
  char    *record,
  long    recordLength,
  char    *recordEncType)
{
  int   i;
  long    rc;
  char    *keys_array[SSA_SI_MAX_KEYS];
  char    keys_data[SSA_SI_MAX_KEYS*SSA_SI_KEY_SZ];
  char    rsp_code[SSA_SI_RSP_SZ];
  char    ssa_msg[SSA_SI_SSA_MSG_SZ];
  long    num;
  char    *p;
  char    *outfname    = "Tagged_Data_output.txt" ;                        // Output File name                
  FILE    *outfile ;                                                       // Object of output file
  outfile = fopen ( outfname , "a" ) ;                                     // Open file and append
  
  if ( ! outfile )  {
    printf ( "Could not open file %s for output\n" ) ;                     // Error message while opening file
    return -1 ;
  }
  for (i = 0; i < (int)rangeof (keys_array); ++i)
    keys_array[i] = keys_data + i * SSA_SI_KEY_SZ;

 /* printf ("------ ssan3_get_keys_encoded ------\n");
  printf ("Session Id       : %ld\n", *session_id);
  printf ("System           : %s\n", sysName);
  printf ("Population       : %s\n", population);
  printf ("Controls         : %s\n", controls);
  printf ("Key field data   : %s\n", record);
  printf ("Key field size   : %ld\n", recordLength);
  printf ("Key field encoding type : %s\n", recordEncType);*/

  num = 0;
  rc = ssan3_get_keys_encoded (
                                sockh,
                                session_id, 
                                sysName, 
                                population, 
                                controls, 
                                rsp_code, 
                                SSA_SI_RSP_SZ, 
                                ssa_msg, 
                                SSA_SI_SSA_MSG_SZ, 
                                record, 
                                recordLength, 
                                recordEncType,
                                &num,
                                keys_array,
                                SSA_SI_KEY_SZ);
    
  if (rc < 0) {
    printf ("rc               : %ld\n", rc);
    rc = 1;
    goto ret;
  }
  if (rsp_code[0] != '0') {
    //printf ("rsp_code         : %s\n", rsp_code);
    //printf ("ssa_msg          : %s\n", ssa_msg);
    rc = -1;
    goto ret;
  }
  
  /*printf ("\n");
  printf ("Session Id       : %ld\n", *session_id);
  printf ("rsp_code         : %s\n", rsp_code);
  printf ("ssa_msg          : %s\n", ssa_msg);
  printf ("Count            : %ld\n", num);*/
  printf ("\n------ keys ------\n");
  for (i = 0; i < num; ++i) {
    p = keys_array[i];
    printf ("%3d '%.*s'\n", i+1, SSA_SI_KEY_SZ, p);
    fputs (("%3d '%.*s'\n", i+1, SSA_SI_KEY_SZ, p) ,outfile ) ;           // Write Key on output file
    fputs("\n",outfile);                                                   // Newline in output file
  }
  
  printf ("\n");
  rc = 0;
  goto ret;

ret:
  return (rc);
}

static long test_ssa_close (
  long    sockh,
  long    *session_id,
  char    *sysName,
  char    *population,
  char    *controls)
{
  long    rc;
  char    rsp_code[SSA_SI_RSP_SZ];
  char    ssa_msg[SSA_SI_SSA_MSG_SZ];

  printf ("------ ssan3_close ------\n");
  printf ("Session Id       : %ld\n", *session_id);
  printf ("System           : %s\n", sysName);
  printf ("Population       : %s\n", population);
  printf ("Controls         : %s\n", controls);

  rc = ssan3_close (sockh,
    session_id,
    sysName,
    population,
    controls,
    rsp_code,
    SSA_SI_RSP_SZ,
    ssa_msg,
    SSA_SI_SSA_MSG_SZ);
  if (rc < 0) {
    printf ("rc               : %ld\n", rc);
    rc = 1;
    goto ret;
  }
  if (rsp_code[0] != '0') {
    printf ("rsp_code         : %s\n", rsp_code);
    printf ("ssa_msg          : %s\n", ssa_msg);
    rc = 1;
    goto ret;
  }
  printf ("\n");
  printf ("Session Id       : %ld\n", *session_id);
  printf ("rsp_code         : %s\n", rsp_code);
  printf ("ssa_msg          : %s\n", ssa_msg);
  rc = 0;
  goto ret;

ret:
  return (rc);
}

static void doExit (char    *func)
{
  printf ("Error occurred in '%s'\n", func);
  exit (EXIT_FAILURE);
}

int main ()
{
  long    rc;
  long    sockh;
  long    session_id;
  
  char    *population  = "India" ;                           // Population
  char    *field       = "FIELD=" ;
  char    *key         = "Person_Name" ;                     // key
  
  //char    *Tagged_data = "*Person_Name*S Kadam***" ;         // Tagged_data
  
  char    *key_level   = "Standard" ;                        // Key level

  char    *infname     = "Tagged_Data.txt" ;                 // Input file name
  FILE    *infile ;
  char line_buffer [ BUFSIZ ] ;
  
  int rec_number       = 0 ;
  infile               = fopen ( infname , "r" ) ;
  sockh                = -1 ;
  session_id           = -1 ;
  
  if ( ! infile ) {
    printf ( "Could not open file %s for input.\n" , infname ) ; 
    return -1 ;
  }

   strcat(field,key);

/* Establish a session.
*/
  rc = test_ssa_open ( sockh, &session_id, "default", population,"");
  if (0 != rc)
    doExit ("test_ssa_open");

/* Call ssan3_get_keys
*/

  while(fgets ( line_buffer , sizeof ( line_buffer ), infile )){
  rc = test_ssa_get_keys (sockh, &session_id, "default", population, field, line_buffer, 23, "TEXT");
  //fputs ( line_buffer ,outfile ) ;
  //printf ("Key level: %s\n",key_level) ;                    //%s for character
  if (0 != rc)
    doExit ("test_ssa_get_keys");
  }
/* Close the previously established session.
*/
  rc = test_ssa_close (
    sockh,
    &session_id,
    "default",
    population,
    "");
  if (0 != rc)
    doExit ("test_ssa_close");

  exit (0);
}
